Development
RockefellerArchiveCenter/cuny-internship-overview pull request #1
Opened 2023-05-05 14:43 UTC by mvassari

Trying to push the RAC-CCNY Internship Program Overview to live site

2023-05-05 17:01 UTC, daremiyo requested changes
Looks good! I requested a small change in the readme

2023-05-05 17:01 UTC, daremiyo commented on README.md
>  A template for docs.rockarch.org documentation repositories. Include a short description of the documentation.
Need to include description here

2023-05-08 13:34 UTC, mvassari reviewed
Hi @daremiyo did my description go through?

2023-05-08 13:34 UTC, mvassari commented on README.md
>  A template for docs.rockarch.org documentation repositories. Include a short description of the documentation.
Updated Readme

2023-05-08 13:34 UTC, mvassari reviewed
Hi @daremiyo did my description go through?

2023-05-08 18:06 UTC, daremiyo approved these changes

2023-05-10 14:44 UTC, merged